### ISSUE TITLE
Segmentation Fault when running anything

### ISSUE THREAD

**Issue by ricardoboss** [libjpeg-turbo/docker#1]
I want to build an image based on `dcommander/buildljt:main`.

My Dockerfile looks like this:

```Dockerfile
FROM dcommander/buildljt:main

RUN yum install git
RUN git clone https://github.com/libjpeg-turbo/buildscripts
RUN cd buildscripts && chmod +x ./buildljt && ./buildljt

CMD ["/bin/bash"]
```

When running `docker build .`, it always exists at the first `RUN` with the message `executor failed running [/bin/sh -c yum install git]: exit code: 139`. Any idea what's wrong here?

**Comment by dcommander** [comment]
It works for me.  :|  It must be something system-specific.  Note, however, that Git is already installed in the `buildljt` image, so you might try removing that command.

I'm also not sure why you are building libjpeg-turbo at the same time as your Docker image.  That will result in a Docker image with a specific build of libjpeg-turbo baked into it.  Generally the purpose of the `buildljt` Docker image is to provide a stable build environment for building any arbitrary libjpeg-turbo commit.  Here is an example of how you might use the `buildljt` Docker image:

```
set -e
set -u

SELINUXARG=
if [ `uname -s` = "Linux" ]; then
	SELINUXARG="--security-opt label=disable"
fi

pushd ~/src
git clone https://github.com/libjpeg-turbo/buildscripts {git_branch_or_tag}
popd

docker run --rm $SELINUXARG -v $HOME/src:/root/src \
	-it dcommander/buildljt:{docker_tag} \
	bash -c "~/src/buildscripts/libjpeg-turbo/buildljt {git_branch_or_tag}"
```

The script above is structurally similar to the script I use when spinning official builds of libjpeg-turbo.  (The main difference is that I left out the package signing stuff, since that requires files that are only accessible on my local build machine.)

The script clones the official libjpeg-turbo build scripts into **~/src** on the host, maps **~/src** on the host to **/root/src** in the container, and invokes the official libjpeg-turbo build scripts in the container.  If successful, the generated build will be under **~/src/ljt.nightly/latest** on the host.
